version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: 'movieflixdb'
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'